/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:wdKernel:831905:
  appc.background(230);
} //_CODE_:wdKernel:831905:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  wdKernel = GWindow.getWindow(this, "View Kernel", 0, 0, 225, 135, JAVA2D);
  wdKernel.noLoop();
  wdKernel.setActionOnClose(G4P.KEEP_OPEN);
  wdKernel.addDrawHandler(this, "win_draw1");
  wdKernel.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow wdKernel;
