/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:cntrlWndw:300958:
  appc.background(230);
} //_CODE_:cntrlWndw:300958:

public void ddType_click(GDropList source, GEvent event) { //_CODE_:ddType:261571:
  if (ddType.getSelectedIndex() == 0){
    axis.reset(-10,10,-10,10,1);
    slider1.setLimits(axis.ymin, axis.ymax);

    slider3.setVisible(false);
    lbSlider3.setVisible(false);
    slider4.setVisible(false);
    lbSlider4.setVisible(false);
    func.setLinear();
    
     c1.populate(-3, -2, 1, 30, Shape.CIRCLE);
     c2.populate(5, 2, 1, 30, Shape.SQUARE);
     
     
  } else if (ddType.getSelectedIndex() == 1){
    axis.reset(-10,10,-10,10,1);
    slider1.setLimits(axis.ymin, axis.ymax);

    func.setQuadratic();
    slider3.setValue(func.param[2]);
    lbSlider3.setText(nf(func.param[2],0,2));
    slider3.setVisible(true);
    lbSlider3.setVisible(true);
    slider4.setVisible(false);
    lbSlider4.setVisible(false);
    
     c1.populate(-5, 7, 1, 20, Shape.CIRCLE);
     c2.populate(3, -1, 1, 10, Shape.CIRCLE);
     c3.populate(-1, -2, 1, 7, Shape.SQUARE);
  } else if (ddType.getSelectedIndex() == 2){
    axis.reset(-10,10,-20,20,1);
    slider1.setLimits(axis.ymin, axis.ymax);

    func.setPoly3();
    slider4.setValue(func.param[3]);
    lbSlider4.setText(nf(func.param[3],0,2));
    slider3.setVisible(true);
    lbSlider3.setVisible(true);
    slider4.setVisible(true);
    lbSlider4.setVisible(true);
    
    c1.populate(-7, 2, 1, 10, Shape.CIRCLE);
    c2.populate(-3, -2, 1, 20, Shape.SQUARE);
    c3.populate(1, 2, 1, 20, Shape.CIRCLE);
    c4.populate(5, -5, 1, 20, Shape.SQUARE);
  }
} //_CODE_:ddType:261571:

public void slider1_change(GCustomSlider source, GEvent event) { //_CODE_:slider1:621782:
  func.setParam(0,slider1.getValueF());
  lbSlider1.setText(nf(slider1.getValueF(),0,2));
} //_CODE_:slider1:621782:

public void slider2_change(GCustomSlider source, GEvent event) { //_CODE_:slider2:420130:
  func.setParam(1,slider2.getValueF());
  lbSlider2.setText(nf(slider2.getValueF(),0,2));
} //_CODE_:slider2:420130:

public void slider3_change(GCustomSlider source, GEvent event) { //_CODE_:slider3:775200:
  func.setParam(2,slider3.getValueF());
  lbSlider3.setText(nf(slider3.getValueF(),0,2));
} //_CODE_:slider3:775200:

public void slider4_change(GCustomSlider source, GEvent event) { //_CODE_:slider4:263354:
  func.setParam(3,slider4.getValueF());
  lbSlider4.setText(nf(slider4.getValueF(),0,2));
} //_CODE_:slider4:263354:

public void btnCluster(GButton source, GEvent event) { //_CODE_:btnClusters:708304:
  if (func.func == FuncType.LINEAR){
     c1.populate(-3, -2, 1, 20, Shape.CIRCLE);
     c2.populate(5, 2, 1, 20, Shape.SQUARE);
  } else if (func.func == FuncType.QUADRATIC){
     c1.populate(-5, 7, 1, 20, Shape.CIRCLE);
     c2.populate(3, -1, 1, 10, Shape.CIRCLE);
     c3.populate(-1, -2, 1, 7, Shape.SQUARE);
  } else if (func.func == FuncType.POLY3){
    c1.populate(-7, 2, 1, 10, Shape.CIRCLE);
    c2.populate(-3, -2, 1, 20, Shape.SQUARE);
    c3.populate(1, 2, 1, 20, Shape.CIRCLE);
    c4.populate(5, 2, 1, 20, Shape.SQUARE);
  }

} //_CODE_:btnClusters:708304:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  cntrlWndw = GWindow.getWindow(this, "Control Window", 0, 0, 240, 240, JAVA2D);
  cntrlWndw.noLoop();
  cntrlWndw.setActionOnClose(G4P.KEEP_OPEN);
  cntrlWndw.addDrawHandler(this, "win_draw1");
  ddType = new GDropList(cntrlWndw, 120, 3, 90, 80, 3, 10);
  ddType.setItems(loadStrings("list_261571"), 0);
  ddType.addEventHandler(this, "ddType_click");
  txtType = new GLabel(cntrlWndw, 3, 3, 105, 20);
  txtType.setText("Function to Fit");
  txtType.setOpaque(false);
  slider1 = new GCustomSlider(cntrlWndw, 5, 36, 187, 20, "grey_blue");
  slider1.setLimits(0.5, 0.0, 1.0);
  slider1.setNumberFormat(G4P.DECIMAL, 2);
  slider1.setOpaque(false);
  slider1.addEventHandler(this, "slider1_change");
  slider2 = new GCustomSlider(cntrlWndw, 5, 62, 187, 20, "grey_blue");
  slider2.setLimits(0.5, 0.0, 1.0);
  slider2.setNumberFormat(G4P.DECIMAL, 2);
  slider2.setOpaque(false);
  slider2.addEventHandler(this, "slider2_change");
  slider3 = new GCustomSlider(cntrlWndw, 5, 88, 188, 20, "grey_blue");
  slider3.setLimits(0.5, 0.0, 1.0);
  slider3.setNumberFormat(G4P.DECIMAL, 2);
  slider3.setOpaque(false);
  slider3.addEventHandler(this, "slider3_change");
  slider4 = new GCustomSlider(cntrlWndw, 5, 114, 189, 20, "grey_blue");
  slider4.setLimits(0.5, 0.0, 1.0);
  slider4.setNumberFormat(G4P.DECIMAL, 2);
  slider4.setOpaque(false);
  slider4.addEventHandler(this, "slider4_change");
  lbSlider1 = new GLabel(cntrlWndw, 193, 35, 43, 20);
  lbSlider1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lbSlider1.setText("0.0");
  lbSlider1.setOpaque(false);
  lbSlider2 = new GLabel(cntrlWndw, 193, 61, 43, 20);
  lbSlider2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lbSlider2.setText("0.0");
  lbSlider2.setOpaque(false);
  lbSlider3 = new GLabel(cntrlWndw, 194, 88, 43, 20);
  lbSlider3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lbSlider3.setText("0.0");
  lbSlider3.setOpaque(false);
  lbSlider4 = new GLabel(cntrlWndw, 195, 113, 43, 20);
  lbSlider4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lbSlider4.setText("0.0");
  lbSlider4.setOpaque(false);
  btnClusters = new GButton(cntrlWndw, 70, 201, 80, 30);
  btnClusters.setText("New Clusters");
  btnClusters.addEventHandler(this, "btnCluster");
  cntrlWndw.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow cntrlWndw;
GDropList ddType; 
GLabel txtType; 
GCustomSlider slider1; 
GCustomSlider slider2; 
GCustomSlider slider3; 
GCustomSlider slider4; 
GLabel lbSlider1; 
GLabel lbSlider2; 
GLabel lbSlider3; 
GLabel lbSlider4; 
GButton btnClusters; 
